server:
    
  #port: 8001 #DEV
  port: 8202 #UAT  #7202 previous
  #port: 8119 #PROD
  tomcat:
   max-threads: 0
   acceptCount: 10000
   max-connections: 10000
  
eureka:
  client:
    service-url:
       ##FOR DEV
       ##OLDdefaultZone: http://10.14.0.34:3011/eureka/
       #defaultZone: http://dev-api.tradebulls.in:3011/eureka/
       ##FOR UAT
       #defaultZone: http://172.20.0.24:8081/eureka/
       defaultZone: http://uat-eureka.tradebulls.in:8081/eureka
       ##FOR PROD
       ##defaultZone: http://172.30.0.25:8081/eureka/
       #defaultZone: http://prod-eureka.tradebulls.in:8081/eureka
  instance:
    prefer-ip-address: true
    
spring:
  application:
    name: ms-aop-scrutiny-process-sanket

environment:
  env: uat
  docpath: \\10.24.0.54\documents\
  
#  env: prod  
#  docpath: \\10.34.0.66\documents\
  
  
  
            
ribbon:
  eureka:
    enabled: true
  restclient:
    enabled: true
  http:
    client:
      enabled: true
  ReadTimeout: 120000
  ConnectTimeout: 120000
        
          
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
          
       
zuul:
  ribbon-isolation-strategy: THREAD

     
feign:
  hystrix:
    enabled: true         

 # Config

app:
 name :  My app ms-aop-scrutiny-process-sanket GIT Repo
 discription :  Welcome to ${app.name}

# Various @value uses like List and Map

my:
 greeting :  Hello World from ms-aop-scrutiny-process-sanket GIT Repo
 list:
  values: One,Two,Three
 name :  sanket
 friends :  rohit sharma, virat kohli, ms dhoni
 info :  "{name : 'sanket', city : 'kolhapur', state : 'maharashtra'}"

db:
 connection: "{ConnectionString:'http://___', userName :'admin', password: 'pass'}"
 host:  199.0.0.1
 port :  1200

# http://localhost:8080/actuator/configprops
management.endpoints.web.exposure.include: "*"

