tbs:
 cache: 
   redis: 
    #ip: 10.10.0.33key
    #ip: 10.90.20.24
    ip: 10.24.0.39
    #ip: 10.30.0.40
    port: 6379
    useSSL: false
    share-native-connection: false
    password: Tbs@Redis@1234

server:
  port: 8203
  
logging:
  file:
    name: D:/Project Exports/CustomerService/elk-stack.log